"""Locals.com login and cookie handling for subscriber access."""
from pathlib import Path


def _to_netscape_string(cookie_data: list[dict]) -> str:
    """Convert Playwright-style cookie list to Netscape cookie file format."""
    lines = []
    for c in cookie_data:
        domain = c.get("domain", "")
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        name = c.get("name", "")
        value = c.get("value", "")
        # Playwright uses "expires" (seconds); session cookies may omit it or use -1
        exp = c.get("expires") or c.get("expirationDate") or 0
        expiry = str(int(exp)) if exp and exp > 0 else "0"
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        lines.append("\t".join([domain, include_sub, path, secure, expiry, name, value]))
    return "\n".join(lines)


def save_cookies_to_file(cookie_data: list[dict], file_path: str | Path) -> None:
    """Write cookies to a Netscape-format file for use with requests/yt-dlp."""
    path = Path(file_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Netscape HTTP Cookie File\n"
        "# https://curl.se/docs/http-cookies.html\n"
        "# This file is generated by the playlist downloader. Do not edit.\n\n"
    )
    path.write_text(header + _to_netscape_string(cookie_data), encoding="utf-8")


def login_and_save_cookies(
    email: str,
    password: str,
    cookies_path: str | Path,
    *,
    headless: bool = True,
    timeout_ms: int = 30_000,
) -> bool:
    """
    Log in to Locals.com with email/password and save session cookies to a file.
    Returns True if login succeeded (we left the login page), False otherwise.
    """
    from playwright.sync_api import sync_playwright

    nav_timeout_ms = max(timeout_ms, 60_000)  # allow time for redirect after login
    cookies_path = Path(cookies_path)
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=headless)
        context = browser.new_context()
        page = context.new_page()
        try:
            print("  Logging in to Locals.com...")
            page.goto("https://locals.com/login", wait_until="domcontentloaded", timeout=timeout_ms)
            # Locals shows "Log in with Email" as disabled until a tab is chosen – force-click to reveal the form
            page.get_by_role("button", name="Log in with Email").click(force=True, timeout=timeout_ms)
            # Wait for email/password inputs to be visible and fill them
            page.wait_for_selector("input[type='email'], input[type='password']", state="visible", timeout=timeout_ms)
            email_sel = "input[type='email']"
            if page.locator(email_sel).count():
                page.fill(email_sel, email)
                page.locator(email_sel).dispatch_event("input")
            else:
                page.fill("input[type='text']", email)
                page.locator("input[type='text']").first.dispatch_event("input")
            page.fill("input[type='password']", password)
            page.locator("input[type='password']").dispatch_event("input")
            # Give the form a moment to enable the submit button (client-side validation)
            page.wait_for_timeout(2000)
            # Submit: enable the button via JS if needed, then click (Locals keeps it disabled until validation)
            page.evaluate("document.querySelector('button[type=submit]')?.removeAttribute('disabled')")
            page.wait_for_timeout(300)
            submit = page.locator("button[type='submit']").first
            submit.click()
            # Wait for navigation away from login (success or error page)
            try:
                page.wait_for_url(lambda url: "/login" not in url, timeout=nav_timeout_ms)
            except Exception as nav_err:
                # Still on login page – show what’s on the page to help debug
                try:
                    body = page.locator("body").inner_text()
                    snippet = body[:400].replace("\n", " ").strip()
                    if snippet:
                        print(f"  Still on login page. Page text (first 400 chars): {snippet}...")
                except Exception:
                    pass
                raise nav_err
            # Still on same origin; get cookies
            cookies = context.cookies()
            save_cookies_to_file(cookies, cookies_path)
            print("  Login succeeded, cookies saved.")
            return True
        except Exception as e:
            print(f"  Login failed: {e}")
            return False
        finally:
            browser.close()
